// Fixed structural text on the print engine's chrome (column headers, section
// titles, footer captions). Per-document text (document title, party label,
// terms) stays free-typed on the Print Profile — this dictionary only covers
// labels every printed document shares.

export type PrintLanguage = "en" | "hi";

export type PrintLabelKey = keyof typeof LABELS_EN;

const LABELS_EN = {
  number: "Number",
  date: "Date",
  time: "Time",
  refNo: "Ref No",
  payment: "Payment",
  placeOfSupply: "Place of Supply",
  reverseCharge: "Reverse Charge",
  yes: "Yes",
  irn: "IRN",
  ackNo: "Ack No",
  ackDate: "Ack Date",
  mobile: "Mobile",
  gstNo: "GST No",
  shipTo: "SHIP TO",
  summary: "SUMMARY",
  subtotal: "Subtotal",
  discount: "Discount",
  tax: "Tax",
  cgst: "CGST",
  sgst: "SGST",
  igst: "IGST",
  grandTotal: "Grand Total",
  transportDetails: "TRANSPORT DETAILS",
  transporter: "Transporter",
  vehicleNo: "Vehicle No",
  lrNo: "LR No",
  ewayBillNo: "E-Way Bill No",
  distance: "Distance (km)",
  validUntil: "Valid Until",
  purposeOfMovement: "Purpose of movement",
  narration: "Narration",
  sr: "Sr",
  partNo: "Part No",
  hsn: "HSN",
  warehouse: "Warehouse",
  description: "Description",
  qty: "Qty",
  mrp: "MRP",
  discPct: "Disc %",
  weight: "Weight",
  rate: "Rate",
  gstPct: "GST %",
  amount: "Amount",
  noItems: "No items",
  ledgerAccount: "Ledger Account",
  debit: "Debit",
  credit: "Credit",
  total: "Total",
  termsConditions: "Terms & Conditions",
  bankDetails: "Bank Details",
  acName: "A/c Name",
  acNo: "A/c No",
  bank: "Bank",
  branch: "Branch",
  ifsc: "IFSC",
  thankYou: "Thank you for your business.",
  authorizedSignature: "Authorized Signature",
  authorizedSignatory: "Authorized Signatory",
  forCompany: "For",
  receivedGoods: "Received the above goods in good condition.",
  receiversSignature: "Receiver's Signature",
} as const;

const LABELS_HI: Record<PrintLabelKey, string> = {
  number: "नंबर",
  date: "दिनांक",
  time: "समय",
  refNo: "संदर्भ सं.",
  payment: "भुगतान",
  placeOfSupply: "आपूर्ति का स्थान",
  reverseCharge: "रिवर्स चार्ज",
  yes: "हाँ",
  irn: "IRN",
  ackNo: "Ack No",
  ackDate: "Ack Date",
  mobile: "मोबाइल",
  gstNo: "जीएसटी नंबर",
  shipTo: "शिप टू",
  summary: "सारांश",
  subtotal: "उप-योग",
  discount: "छूट",
  tax: "कर",
  cgst: "सीजीएसटी",
  sgst: "एसजीएसटी",
  igst: "आईजीएसटी",
  grandTotal: "कुल योग",
  transportDetails: "परिवहन विवरण",
  transporter: "ट्रांसपोर्टर",
  vehicleNo: "वाहन संख्या",
  lrNo: "एलआर संख्या",
  ewayBillNo: "ई-वे बिल संख्या",
  distance: "Distance (km)",
  validUntil: "Valid Until",
  purposeOfMovement: "आवागमन का उद्देश्य",
  narration: "विवरण",
  sr: "क्र.",
  partNo: "पार्ट नंबर",
  hsn: "एचएसएन",
  warehouse: "गोदाम",
  description: "विवरण",
  qty: "मात्रा",
  mrp: "एमआरपी",
  discPct: "छूट %",
  weight: "वज़न",
  rate: "दर",
  gstPct: "जीएसटी %",
  amount: "राशि",
  noItems: "कोई वस्तु नहीं",
  ledgerAccount: "लेजर खाता",
  debit: "डेबिट",
  credit: "क्रेडिट",
  total: "कुल",
  termsConditions: "नियम एवं शर्तें",
  bankDetails: "बैंक विवरण",
  acName: "खाता नाम",
  acNo: "खाता संख्या",
  bank: "बैंक",
  branch: "शाखा",
  ifsc: "आईएफएससी",
  thankYou: "आपके व्यापार के लिए धन्यवाद।",
  authorizedSignature: "अधिकृत हस्ताक्षर",
  authorizedSignatory: "अधिकृत हस्ताक्षरकर्ता",
  forCompany: "हेतु",
  receivedGoods: "उपरोक्त माल अच्छी स्थिति में प्राप्त हुआ।",
  receiversSignature: "प्राप्तकर्ता के हस्ताक्षर",
};

export function getPrintLabels(language: PrintLanguage = "en"): Record<PrintLabelKey, string> {
  return language === "hi" ? LABELS_HI : LABELS_EN;
}
