-- Fix: trg_prevent_posted_voucher_delete (restore_posted_voucher_delete_guard,
-- 2026-08-09) blocks hard-deleting ANY posted voucher with a non-null
-- reference_type, on the assumption every reference_type means "this voucher
-- was auto-generated by a source document elsewhere -- cancel/unlink that
-- document instead." That assumption predates 'opening_balance_adjustment'
-- (introduced 2026-08-18, phase3_opening_balance_migration.sql's
-- mig_create_adjustment): those vouchers are standalone correcting journals
-- created directly by the user from the Opening Balance Migration wizard's
-- Adjustments panel, with reference_id only an informational back-link to
-- the original Opening Balance Voucher for traceability -- there is no
-- separate source document to cancel elsewhere. The guard's blanket rule
-- left every posted opening-balance-adjustment permanently undeletable,
-- defeating that panel's own Delete action (confirmed live: every attempt
-- returned "This voucher was auto-generated from a opening_balance_adjustment.
-- Cancel or unlink the source document first."). Fix: treat
-- 'opening_balance_adjustment' the same as NULL -- deletable directly, still
-- subject to the child-row reference check below. document_dependency_report()
-- (hard_delete_document.sql) mirrors this same exemption so the pre-flight
-- confirmation dialog and the actual trigger never disagree.
--
-- 'migration_opening_balance' (the original Opening Balance Voucher itself)
-- is deliberately NOT exempted here -- it already has its own dedicated lock
-- (enforce_opening_balance_voucher_lock()) and genuinely should only be
-- corrected via an adjustment, never hard-deleted directly.

CREATE OR REPLACE FUNCTION public.prevent_posted_voucher_delete()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_linked_count integer := 0;
BEGIN
  IF OLD.status = 'posted' THEN
    IF OLD.reference_type IS NOT NULL AND OLD.reference_type <> 'opening_balance_adjustment' THEN
      RAISE EXCEPTION 'Cannot hard-delete posted voucher % -- it was generated from a %. Cancel or unlink the source document first.', OLD.voucher_number, OLD.reference_type
        USING ERRCODE = '23503';
    END IF;

    SELECT
        (SELECT count(*) FROM public.sales_invoices WHERE voucher_id = OLD.id)
      + (SELECT count(*) FROM public.purchase_invoices WHERE voucher_id = OLD.id)
      + (SELECT count(*) FROM public.payment_entries WHERE voucher_id = OLD.id)
      + (SELECT count(*) FROM public.purchase_returns WHERE voucher_id = OLD.id)
      + (SELECT count(*) FROM public.sales_returns WHERE voucher_id = OLD.id)
      + (SELECT count(*) FROM public.inventory_adjustments WHERE voucher_id = OLD.id)
    INTO v_linked_count;

    IF v_linked_count > 0 THEN
      RAISE EXCEPTION 'Cannot hard-delete posted voucher % -- % linked document(s) still reference it. Unlink or cancel them first.', OLD.voucher_number, v_linked_count
        USING ERRCODE = '23503';
    END IF;
  END IF;

  RETURN OLD;
END;
$function$;

CREATE OR REPLACE FUNCTION public.document_dependency_report(_doc_type text, _doc_id uuid)
  RETURNS jsonb
  LANGUAGE plpgsql
  STABLE
  SECURITY DEFINER
  SET search_path TO 'public'
AS $fn$
DECLARE
  v_business_id uuid;
  v_status text;
  v_reference_type text;
  v_blocking jsonb := '[]'::jsonb;
  v_count integer;
BEGIN
  IF _doc_type <> 'voucher' THEN
    RAISE EXCEPTION 'document_dependency_report: doc_type % not yet supported', _doc_type;
  END IF;

  SELECT business_id, status, reference_type INTO v_business_id, v_status, v_reference_type
  FROM public.vouchers WHERE id = _doc_id;

  IF v_business_id IS NULL THEN
    RAISE EXCEPTION 'Voucher not found';
  END IF;
  IF NOT public.is_business_member(v_business_id) THEN
    RAISE EXCEPTION 'Access denied';
  END IF;

  IF v_status <> 'posted' THEN
    RETURN jsonb_build_object('can_hard_delete', true, 'blocking', '[]'::jsonb);
  END IF;

  IF v_reference_type IS NOT NULL AND v_reference_type <> 'opening_balance_adjustment' THEN
    v_blocking := v_blocking || jsonb_build_object(
      'table', v_reference_type, 'message',
      format('This voucher was auto-generated from a %s. Cancel or unlink the source document first.', v_reference_type)
    );
  END IF;

  SELECT count(*) INTO v_count FROM public.sales_invoices WHERE voucher_id = _doc_id;
  IF v_count > 0 THEN v_blocking := v_blocking || jsonb_build_object('table', 'sales_invoices', 'count', v_count, 'message', format('Referenced by %s Sales Invoice(s).', v_count)); END IF;

  SELECT count(*) INTO v_count FROM public.purchase_invoices WHERE voucher_id = _doc_id;
  IF v_count > 0 THEN v_blocking := v_blocking || jsonb_build_object('table', 'purchase_invoices', 'count', v_count, 'message', format('Referenced by %s Purchase Invoice(s).', v_count)); END IF;

  SELECT count(*) INTO v_count FROM public.payment_entries WHERE voucher_id = _doc_id;
  IF v_count > 0 THEN v_blocking := v_blocking || jsonb_build_object('table', 'payment_entries', 'count', v_count, 'message', format('Referenced by %s Payment/Receipt entr(y/ies).', v_count)); END IF;

  SELECT count(*) INTO v_count FROM public.purchase_returns WHERE voucher_id = _doc_id;
  IF v_count > 0 THEN v_blocking := v_blocking || jsonb_build_object('table', 'purchase_returns', 'count', v_count, 'message', format('Referenced by %s Purchase Return(s).', v_count)); END IF;

  SELECT count(*) INTO v_count FROM public.sales_returns WHERE voucher_id = _doc_id;
  IF v_count > 0 THEN v_blocking := v_blocking || jsonb_build_object('table', 'sales_returns', 'count', v_count, 'message', format('Referenced by %s Sales Return(s).', v_count)); END IF;

  SELECT count(*) INTO v_count FROM public.inventory_adjustments WHERE voucher_id = _doc_id;
  IF v_count > 0 THEN v_blocking := v_blocking || jsonb_build_object('table', 'inventory_adjustments', 'count', v_count, 'message', format('Referenced by %s Inventory Adjustment(s).', v_count)); END IF;

  RETURN jsonb_build_object('can_hard_delete', jsonb_array_length(v_blocking) = 0, 'blocking', v_blocking);
END;
$fn$;

REVOKE ALL ON FUNCTION public.document_dependency_report(text, uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.document_dependency_report(text, uuid) TO authenticated;
