// src/lib/navigation/registry.ts
//
// ============================================================================
// CENTRAL NAVIGATION REGISTRY
// ============================================================================
// This is the ONLY place page metadata is defined. The Sidebar, the Command
// Search, Breadcrumbs, Favorites and Recent Pages all derive from this array
// via `useNavigation()` (see ./useNavigation.ts). To add a new page to the
// whole app — sidebar AND search AND breadcrumbs — add one entry here.
//
// Nesting: set `parentId` to make an item a child of another item (which can
// itself have a parent), so the tree can go arbitrarily deep. Items without
// a `route` act purely as group headers (e.g. "Vouchers" inside "Accounts").
// ============================================================================

import {
  LayoutDashboard,
  Calculator,
  History,
  User,
  Users,
  ShoppingCart,
  PlusSquare,
  Package,
  Boxes,
  BarChart3,
  Settings as SettingsIcon,
  BookOpen,
  FileSpreadsheet,
  Receipt,
  Scale,
  Wallet,
  Landmark,
  ArrowUpRight,
  ArrowDownRight,
  PieChart,
  ShieldCheck,
  ClipboardList,
  Building2,
  Repeat,
  ShoppingBag,
  TruckIcon,
  FileText,
  CreditCard,
  FilePlus,
  UploadCloud,
  Tags,
  Barcode,
  Layers,
  ScanLine,
  LayoutGrid,
  AlertTriangle,
  Archive,
  Zap,
  Clock,
  Activity,
} from "lucide-react";
import type { NavItem } from "./types";

export const NAV_ITEMS: NavItem[] = [
  // ==========================================================================
  // DASHBOARD
  // ==========================================================================
  {
    id: "dashboard",
    title: "Dashboard",
    description: "Business overview, key metrics and shortcuts",
    route: "/dashboard",
    icon: LayoutDashboard,
    module: "Dashboard",
    keywords: ["home", "overview", "summary"],
  },
  {
    id: "calculator",
    title: "RD Calculator",
    description: "Rate & discount calculator",
    route: "/calculator",
    icon: Calculator,
    module: "Dashboard",
    keywords: ["rate", "discount", "calc"],
  },
  {
    id: "reports",
    title: "Business Analytics",
    description: "Reports and business performance insights",
    route: "/reports",
    icon: BarChart3,
    module: "Reports",
    aliases: ["analytics", "insights"],
    showInSidebar: false,
  },
  {
    id: "reports-center",
    title: "Report Center",
    description: "Browse every report by category, search, and open with one click",
    route: "/reports/center",
    icon: LayoutGrid,
    module: "Reports",
  },
  {
    id: "history",
    title: "History",
    description: "Order and transaction history",
    route: "/history",
    icon: History,
    module: "Reports",
    keywords: ["past orders", "activity"],
    showInSidebar: false,
  },
  {
    id: "reports-sales-register",
    title: "Sales Register",
    description: "All sales invoices for a date range, with GST breakdown",
    route: "/reports/sales-register",
    icon: FileText,
    module: "Reports",
    keywords: ["sales", "invoices", "register"],
    showInSidebar: false,
  },
  {
    id: "reports-purchase-register",
    title: "Purchase Register",
    description: "All purchase invoices for a date range, supplier-wise",
    route: "/reports/purchase-register",
    icon: Receipt,
    module: "Reports",
    keywords: ["purchase", "invoices", "supplier"],
    showInSidebar: false,
  },
  {
    id: "reports-outstanding-ageing",
    title: "Outstanding Ageing",
    description: "Unpaid invoices bucketed by age (0-30, 31-60, 61-90, 90+)",
    route: "/reports/outstanding-ageing",
    icon: CreditCard,
    module: "Reports",
    keywords: ["outstanding", "ageing", "aging", "overdue", "receivables"],
    showInSidebar: false,
  },

  // ==========================================================================
  // SALES
  // ==========================================================================
  {
    id: "orders-new",
    title: "Create Order",
    description: "Start a new sales order",
    route: "/orders/new",
    icon: PlusSquare,
    module: "Sales",
    quickAction: { label: "Create Order", shortcut: "⌘N" },
    perm: "voucher.create",
  },
  {
    id: "orders",
    title: "Orders",
    description: "All sales orders",
    route: "/orders",
    icon: ShoppingCart,
    module: "Sales",
  },
  {
    id: "pending",
    title: "Pending Orders",
    description: "Orders awaiting dispatch or approval",
    route: "/pending",
    icon: Boxes,
    module: "Sales",
    keywords: ["awaiting", "open orders"],
  },
  {
    id: "dispatch",
    title: "Dispatch",
    description: "Dispatch management",
    route: "/dispatch",
    icon: Package,
    module: "Sales",
    keywords: ["shipment", "delivery"],
  },
  {
    id: "sales-invoices",
    title: "Sales Invoices",
    description: "All sales invoices",
    route: "/sales/invoices",
    icon: Receipt,
    module: "Sales",
    aliases: ["bills"],
  },
  {
    id: "sales-receive-payment",
    title: "Receive Payment",
    description: "Record a customer payment and allocate it against specific invoices (bill-wise)",
    route: "/sales/receive-payment",
    icon: CreditCard,
    module: "Sales",
    keywords: ["receipt", "collection", "bill-wise"],
  },
  {
    id: "excel-import",
    title: "Excel Import",
    description: "Bulk import orders from Excel",
    route: "/excel-import",
    icon: UploadCloud,
    module: "Sales",
    keywords: ["bulk", "csv", "upload", "xlsx"],
  },
  {
    id: "parties",
    title: "Customers",
    description: "Customer / party master list",
    route: "/parties",
    icon: Users,
    module: "Sales",
    aliases: ["parties", "clients", "buyers"],
  },
  {
    id: "party-groups",
    title: "Party Groups",
    description: "Group customers/suppliers for pricing & reporting",
    route: "/masters/party-groups",
    icon: Users,
    module: "Sales",
    keywords: ["masters", "grouping"],
  },
  {
    id: "sales-config",
    title: "Sales Configuration",
    description: "Configure sales workflow defaults",
    route: "/settings/sales-config",
    icon: SettingsIcon,
    module: "Sales",
    keywords: ["config", "settings"],
    perm: "settings.edit",
  },

  // ==========================================================================
  // PURCHASE
  // ==========================================================================
  {
    id: "purchase-dashboard",
    title: "Purchase Dashboard",
    description: "Purchase overview",
    route: "/purchase",
    icon: ShoppingBag,
    module: "Purchase",
  },
  {
    id: "purchase-orders",
    title: "Purchase Orders",
    description: "All purchase orders",
    route: "/purchase/orders",
    icon: ClipboardList,
    module: "Purchase",
    aliases: ["po"],
  },
  {
    id: "purchase-orders-new",
    title: "Create Purchase Order",
    description: "Raise a new purchase order",
    route: "/purchase/orders/new",
    icon: PlusSquare,
    module: "Purchase",
    quickAction: { label: "Create Purchase" },
    perm: "purchase.create",
  },
  {
    id: "purchase-grn",
    title: "Goods Receipt Note",
    description: "Record goods received against a purchase order",
    route: "/purchase/grn",
    icon: TruckIcon,
    module: "Purchase",
    aliases: ["grn"],
  },
  {
    id: "purchase-invoices",
    title: "Purchase Invoices",
    description: "All purchase invoices",
    route: "/purchase/invoices",
    icon: FileText,
    module: "Purchase",
  },
  {
    id: "purchase-returns",
    title: "Purchase Returns",
    description: "Return goods to a supplier",
    route: "/purchase/returns",
    icon: Repeat,
    module: "Purchase",
  },
  {
    id: "purchase-approvals",
    title: "Purchase Approvals",
    description: "Approve or reject pending purchases",
    route: "/purchase/approvals",
    icon: ShieldCheck,
    module: "Purchase",
    perm: "purchase.approve",
  },
  {
    id: "purchase-payments",
    title: "Supplier Payments",
    description: "Payments made to suppliers",
    route: "/purchase/payments",
    icon: CreditCard,
    module: "Purchase",
  },
  {
    id: "purchase-reports",
    title: "Purchase Reports",
    description: "Purchase analytics and reports",
    route: "/purchase/reports",
    icon: BarChart3,
    module: "Purchase",
    showInSidebar: false,
  },
  {
    id: "supplier-ledger",
    title: "Supplier Ledger",
    description: "Supplier-wise transaction ledger",
    route: "/purchase/supplier-ledger",
    icon: BookOpen,
    module: "Purchase",
  },

  // ==========================================================================
  // INVENTORY
  // ==========================================================================
  {
    id: "products",
    title: "Products",
    description: "Product master list",
    route: "/products",
    icon: Package,
    module: "Inventory",
    quickAction: { label: "Create Product" },
    aliases: ["items", "sku"],
  },
  {
    id: "products-bulk-gst",
    title: "Bulk GST Assign",
    description: "Assign GST rates to products in bulk",
    route: "/products/bulk-gst",
    icon: Tags,
    module: "Inventory",
    keywords: ["gst", "tax", "bulk"],
  },
  {
    id: "inventory",
    title: "Inventory",
    description: "Current stock levels",
    route: "/inventory",
    icon: Boxes,
    module: "Inventory",
    aliases: ["stock"],
  },
  {
    id: "inventory-warehouses",
    title: "Warehouses",
    description: "Manage warehouse locations",
    route: "/inventory/warehouses",
    icon: Building2,
    module: "Inventory",
  },
  {
    id: "inventory-batches",
    title: "Batch Tracking",
    description: "Track stock by batch/lot",
    route: "/inventory/batches",
    icon: Layers,
    module: "Inventory",
    aliases: ["lots"],
  },
  {
    id: "inventory-serials",
    title: "Serial Numbers",
    description: "Track stock by serial number",
    route: "/inventory/serials",
    icon: FilePlus,
    module: "Inventory",
  },
  {
    id: "inventory-barcodes",
    title: "Barcodes",
    description: "Generate and print product barcodes",
    route: "/inventory/barcodes",
    icon: Barcode,
    module: "Inventory",
  },
  {
    id: "inventory-transfers",
    title: "Stock Transfers",
    description: "Move stock between warehouses",
    route: "/inventory/transfers",
    icon: Repeat,
    module: "Inventory",
  },
  {
    id: "inventory-stock-take",
    title: "Physical Stock",
    description: "Physical stock take / count",
    route: "/inventory/stock-take",
    icon: ScanLine,
    module: "Inventory",
    aliases: ["stock take", "count"],
  },
  {
    id: "inventory-adjustments",
    title: "Stock Adjustments",
    description: "Adjust stock for damage, loss, etc.",
    route: "/inventory/adjustments",
    icon: Scale,
    module: "Inventory",
  },

  // ==========================================================================
  // ACCOUNTS (nested: Vouchers / Books / Reports / Receivables & Payables)
  // ==========================================================================
  {
    id: "accounts-vouchers-group",
    title: "Vouchers",
    module: "Accounts",
    description: "Create and manage accounting vouchers",
  },
  {
    id: "accounts-books-group",
    title: "Books & Registers",
    module: "Accounts",
    description: "Day book, cash book and bank book",
  },
  {
    id: "accounts-reports-group",
    title: "Financial Reports",
    module: "Accounts",
    description: "Trial balance, P&L, balance sheet and cash flow",
  },
  {
    id: "accounts-outstanding-group",
    title: "Receivables & Payables",
    module: "Accounts",
    description: "Outstanding dues to be collected or paid",
    showInSidebar: false,
  },

  {
    id: "accounts-voucher-center",
    title: "Voucher Center",
    description: "Central hub for all voucher types",
    route: "/accounts/vouchers",
    icon: Receipt,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
  },
  {
    id: "accounting-vouchers",
    title: "Vouchers",
    description: "Browse all posted vouchers",
    route: "/accounting/vouchers",
    icon: FilePlus,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
  },
  {
    id: "accounting-vouchers-new",
    title: "New Voucher",
    description: "Create a new accounting voucher",
    route: "/accounting/vouchers/new",
    icon: PlusSquare,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    quickAction: { label: "Create Voucher" },
    perm: "voucher.create",
  },
  {
    id: "accounts-journal",
    title: "Journal Voucher",
    description: "Record a journal entry",
    route: "/accounts/journal",
    icon: FilePlus,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    aliases: ["jv"],
    perm: "voucher.create",
  },
  {
    id: "accounts-contra",
    title: "Contra Voucher",
    description: "Cash ↔ bank transfer entry",
    route: "/accounts/contra",
    icon: Repeat,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    perm: "voucher.create",
  },
  {
    id: "accounts-payment",
    title: "Payment Voucher",
    description: "Record an outgoing payment",
    route: "/accounts/payment",
    icon: ArrowDownRight,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    perm: "voucher.create",
  },
  {
    id: "accounts-receipt",
    title: "Receipt Voucher",
    description: "Record an incoming payment",
    route: "/accounts/receipt",
    icon: ArrowUpRight,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    perm: "voucher.create",
  },
  {
    id: "accounts-debit-note",
    title: "Debit Note",
    description: "Issue a debit note",
    route: "/accounts/debit-note",
    icon: FileText,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    perm: "voucher.create",
  },
  {
    id: "accounts-credit-note",
    title: "Credit Note",
    description: "Issue a credit note",
    route: "/accounts/credit-note",
    icon: FileText,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    perm: "voucher.create",
  },

  {
    id: "accounts-ledgers",
    title: "Ledger Accounts",
    description: "Chart of accounts and party ledgers",
    route: "/accounts/ledgers",
    icon: BookOpen,
    module: "Accounts",
    aliases: ["ledger", "coa"],
  },
  {
    id: "accounts-day-book",
    title: "Day Book",
    description: "All transactions for a given day",
    route: "/accounts/day-book",
    icon: ClipboardList,
    module: "Accounts",
    parentId: "accounts-books-group",
  },
  {
    id: "accounts-cash-book",
    title: "Cash Book",
    description: "Cash transaction register",
    route: "/accounts/cash-book",
    icon: Wallet,
    module: "Accounts",
    parentId: "accounts-books-group",
  },
  {
    id: "accounts-bank-book",
    title: "Bank Book",
    description: "Bank transaction register",
    route: "/accounts/bank-book",
    icon: Landmark,
    module: "Accounts",
    parentId: "accounts-books-group",
  },
  {
    id: "accounts-bank-accounts",
    title: "Bank Accounts",
    description: "Manage your bank accounts — each gets its own ledger automatically",
    route: "/accounts/bank-accounts",
    icon: Landmark,
    module: "Accounts",
    parentId: "accounts-books-group",
    keywords: ["ifsc", "account number", "banking"],
  },

  {
    id: "accounts-trial-balance",
    title: "Trial Balance",
    description: "Trial balance report",
    route: "/accounts/trial-balance",
    icon: Scale,
    module: "Accounts",
    parentId: "accounts-reports-group",
    showInSidebar: false,
  },
  {
    id: "accounts-profit-loss",
    title: "Profit & Loss",
    description: "Profit and loss statement",
    route: "/accounts/profit-loss",
    icon: PieChart,
    module: "Accounts",
    parentId: "accounts-reports-group",
    aliases: ["p&l", "pnl", "income statement"],
    showInSidebar: false,
  },
  {
    id: "accounts-balance-sheet",
    title: "Balance Sheet",
    description: "Balance sheet report",
    route: "/accounts/balance-sheet",
    icon: FileSpreadsheet,
    module: "Accounts",
    parentId: "accounts-reports-group",
    showInSidebar: false,
  },
  {
    id: "accounts-cash-flow",
    title: "Cash Flow",
    description: "Cash flow statement",
    route: "/accounts/cash-flow",
    icon: PieChart,
    module: "Accounts",
    parentId: "accounts-reports-group",
    // NOT hidden / NOT in Report Center yet -- this page is still mock
    // (verified: 0 real Supabase calls). Stays in the sidebar under its
    // native "Financial Reports" group until it's wired to real data,
    // per the no-mock-in-Report-Center rule.
  },

  {
    id: "accounts-receivables",
    title: "Receivables",
    description: "Amounts owed to you",
    route: "/accounts/receivables",
    icon: ArrowUpRight,
    module: "Accounts",
    parentId: "accounts-outstanding-group",
    aliases: ["debtors"],
    showInSidebar: false,
  },
  {
    id: "accounts-payables",
    title: "Payables",
    description: "Amounts you owe suppliers",
    route: "/accounts/payables",
    icon: ArrowDownRight,
    module: "Accounts",
    parentId: "accounts-outstanding-group",
    aliases: ["creditors"],
    showInSidebar: false,
  },

  // ==========================================================================
  // INVENTORY REPORTS
  // ==========================================================================
  {
    id: "inv-reports-group",
    title: "Inventory Reports",
    module: "Reports",
    description: "Tally-style inventory reports with drill-down",
    showInSidebar: false,
  },
  {
    id: "inv-reports-dashboard",
    title: "Inventory Dashboard",
    description: "Live stock health — KPIs, alerts and quick links to all inventory reports",
    route: "/reports/inventory",
    icon: Package,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    keywords: ["stock", "inventory", "dashboard", "kpi", "overview"],
  },
  {
    id: "inv-stock-summary",
    title: "Stock Summary",
    description: "Opening · Inward · Outward · Closing with drill-down to every transaction — Tally-style",
    route: "/reports/inventory/stock-summary",
    icon: FileSpreadsheet,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    keywords: ["stock", "summary", "opening", "closing", "inward", "outward", "tally", "stock report"],
    aliases: ["stock summary", "stock report", "inventory summary"],
  },
  {
    id: "inv-group-summary",
    title: "Stock Group Summary",
    description: "Stock movement summarised by product group",
    route: "/reports/inventory/group-summary",
    icon: Boxes,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    keywords: ["group", "product group", "stock group"],
  },
  {
    id: "inv-category-summary",
    title: "Stock Category Summary",
    description: "Stock movement summarised by product category",
    route: "/reports/inventory/category-summary",
    icon: Boxes,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    keywords: ["category", "stock category", "category summary"],
  },
  {
    id: "inv-warehouse-summary",
    title: "Warehouse Summary",
    description: "Stock levels and movement per warehouse location",
    route: "/reports/inventory/warehouse-summary",
    icon: Building2,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    keywords: ["warehouse", "location", "godown", "stock"],
  },
  {
    id: "inv-stock-ageing",
    title: "Stock Ageing",
    description: "Stock classified by days since last movement — 0-30, 31-60, 61-90, 90-180, 180-365, 365+",
    route: "/reports/inventory/stock-ageing",
    icon: Clock,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    keywords: ["ageing", "aging", "old stock", "slow moving", "days"],
  },
  {
    id: "inv-dead-stock",
    title: "Dead Stock Report",
    description: "Products with no outward movement for configurable days — identify idle inventory",
    route: "/reports/inventory/dead-stock",
    icon: AlertTriangle,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    keywords: ["dead stock", "idle", "non moving", "stuck inventory"],
  },
  {
    id: "inv-movement-register",
    title: "Stock Movement Register",
    description: "All stock inflows and outflows — Purchase, Sales, Transfers, Adjustments, Returns",
    route: "/reports/inventory/movement-register",
    icon: Activity,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    keywords: ["movement", "register", "inward", "outward", "purchase", "sales", "transfer", "stock ledger"],
    aliases: ["stock ledger", "movement register", "stock register"],
  },
  {
    id: "inv-stock-valuation",
    title: "Stock Valuation",
    description: "Closing stock valued at cost, MRP and selling price with profit potential",
    route: "/reports/inventory/stock-valuation",
    icon: Archive,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    keywords: ["valuation", "value", "cost", "mrp", "profit", "stock value"],
  },
  {
    id: "inv-abc-analysis",
    title: "ABC Analysis",
    description: "Pareto classification — A = top 80% of value, B = next 15%, C = bottom 5%",
    route: "/reports/inventory/abc-analysis",
    icon: BarChart3,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    keywords: ["abc", "pareto", "80-20", "classification", "analysis"],
  },
  {
    id: "inv-fsn-analysis",
    title: "FSN Analysis",
    description: "Fast · Slow · Non-moving classification by sales movement frequency",
    route: "/reports/inventory/fsn-analysis",
    icon: Zap,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    keywords: ["fsn", "fast", "slow", "non moving", "frequency", "velocity"],
  },

  // ==========================================================================
  // GST
  // ==========================================================================
  {
    id: "gst-summary",
    title: "GST Summary",
    description: "GST liability and input tax credit summary",
    route: "/gst/summary",
    icon: FileSpreadsheet,
    module: "GST",
    keywords: ["tax", "gstr", "returns"],
    showInSidebar: false,
  },

  // ==========================================================================
  // ADMINISTRATION
  // ==========================================================================
  {
    id: "approval-center",
    title: "Approval Center",
    description: "Pending approvals across modules",
    route: "/approval-center",
    icon: ShieldCheck,
    module: "Administration",
  },
  {
    id: "audit-logs",
    title: "Audit Logs",
    description: "System-wide audit trail",
    route: "/admin/audit-logs",
    icon: ShieldCheck,
    module: "Administration",
    perm: "audit.view",
  },
  {
    id: "voucher-numbering",
    title: "Voucher Numbering",
    description: "Configure voucher numbering series",
    route: "/settings/voucher-numbering",
    icon: Receipt,
    module: "Administration",
    perm: "settings.edit",
  },
  {
    id: "accounting-lock",
    title: "Accounting Lock",
    description: "Lock accounting periods from further edits",
    route: "/settings/accounting-lock",
    icon: ShieldCheck,
    module: "Administration",
    perm: "settings.edit",
  },
  {
    id: "dealer-applications",
    title: "Dealer Applications",
    description: "Review incoming dealer/retailer applications",
    route: "/settings/dealer-applications",
    icon: ClipboardList,
    module: "Administration",
    perm: "settings.edit",
  },

  // ==========================================================================
  // CONFIGURATION (business-level setup)
  // ==========================================================================
  {
    id: "business-profile",
    title: "Business Profile",
    description: "Company details, GSTIN, PAN, bank info",
    route: "/settings/business-profile",
    icon: Landmark,
    module: "Configuration",
    perm: "business.edit",
  },
  {
    id: "company-users",
    title: "Company Users",
    description: "Manage users in this company",
    route: "/settings/company-users",
    icon: Users,
    module: "Configuration",
    perm: "team.manage",
  },
  {
    id: "team",
    title: "Team & Roles",
    description: "Manage team members and their roles",
    route: "/settings/team",
    icon: Users,
    module: "Configuration",
    perm: "team.manage",
  },

  // ==========================================================================
  // SETTINGS (personal account)
  // ==========================================================================
  {
    id: "profile",
    title: "Profile",
    description: "Your personal profile",
    route: "/profile",
    icon: User,
    module: "Settings",
  },
  {
    id: "settings",
    title: "Settings",
    description: "App preferences",
    route: "/settings",
    icon: SettingsIcon,
    module: "Settings",
  },
];
