// src/lib/navigation/registry.ts
//
// ============================================================================
// CENTRAL NAVIGATION REGISTRY
// ============================================================================
// This is the ONLY place page metadata is defined. The Sidebar, the Command
// Search, Breadcrumbs, Favorites and Recent Pages all derive from this array
// via `useNavigation()` (see ./useNavigation.ts). To add a new page to the
// whole app — sidebar AND search AND breadcrumbs — add one entry here.
//
// Nesting: set `parentId` to make an item a child of another item (which can
// itself have a parent), so the tree can go arbitrarily deep. Items without
// a `route` act purely as group headers (e.g. "Vouchers" inside "Accounts").
// ============================================================================

import {
  LayoutDashboard,
  Calculator,
  History,
  User,
  Users,
  ShoppingCart,
  PlusSquare,
  Package,
  Boxes,
  BarChart3,
  Settings as SettingsIcon,
  BookOpen,
  FileSpreadsheet,
  Receipt,
  Scale,
  Wallet,
  Landmark,
  ArrowUpRight,
  ArrowDownRight,
  PieChart,
  ShieldCheck,
  ClipboardList,
  Building2,
  Repeat,
  ShoppingBag,
  TruckIcon,
  FileText,
  CreditCard,
  FilePlus,
  UploadCloud,
  Tags,
  Barcode,
  Layers,
  ScanLine,
  LayoutGrid,
  AlertTriangle,
  Archive,
  Zap,
  Clock,
  Activity,
  ArrowLeftRight,
  DatabaseBackup,
  Wrench,
  ShieldAlert,
  HelpCircle,
  Keyboard,
  Mail,
} from "lucide-react";
import type { NavItem } from "./types";

export const NAV_ITEMS: NavItem[] = [
  // ==========================================================================
  // DASHBOARD
  // ==========================================================================
  {
    id: "dashboard",
    title: "Dashboard",
    description: "Business overview, key metrics and shortcuts",
    route: "/dashboard",
    icon: LayoutDashboard,
    module: "Dashboard",
    keywords: ["home", "overview", "summary"],
    // Empty path = a leaf directly at the Gateway root (not nested inside a
    // "Dashboard" group you'd have to drill into first).
    gatewayPath: [],
  },
  {
    id: "calculator",
    title: "RD Calculator",
    description: "Rate & discount calculator",
    route: "/calculator",
    icon: Calculator,
    module: "Dashboard",
    keywords: ["rate", "discount", "calc"],
    gatewayPath: ["Utilities"],
  },
  {
    id: "reports",
    title: "Business Analytics",
    description: "Reports and business performance insights",
    route: "/reports",
    icon: BarChart3,
    module: "Reports",
    aliases: ["analytics", "insights"],
    showInSidebar: false,
  },
  {
    id: "reports-center",
    title: "Report Center",
    description: "Browse every report by category, search, and open with one click",
    route: "/reports/center",
    icon: LayoutGrid,
    module: "Reports",
    gatewayPath: ["Reports"],
  },
  {
    id: "history",
    title: "History",
    description: "Order and transaction history",
    route: "/history",
    icon: History,
    module: "Reports",
    keywords: ["past orders", "activity"],
    showInSidebar: false,
    gatewayPath: ["Reports"],
  },
  {
    id: "reports-sales-register",
    title: "Sales Register",
    description: "All sales invoices for a date range, with GST breakdown",
    route: "/reports/sales-register",
    icon: FileText,
    module: "Reports",
    keywords: ["sales", "invoices", "register"],
    showInSidebar: false,
    gatewayPath: ["Reports", "Sales"],
  },
  {
    id: "reports-purchase-register",
    title: "Purchase Register",
    description: "All purchase invoices for a date range, supplier-wise",
    route: "/reports/purchase-register",
    icon: Receipt,
    module: "Reports",
    keywords: ["purchase", "invoices", "supplier"],
    showInSidebar: false,
    gatewayPath: ["Reports", "Purchase"],
  },
  {
    id: "reports-outstanding-ageing",
    title: "Outstanding Ageing",
    description: "Unpaid invoices bucketed by age (0-30, 31-60, 61-90, 90+)",
    route: "/reports/outstanding-ageing",
    icon: CreditCard,
    module: "Reports",
    keywords: ["outstanding", "ageing", "aging", "overdue", "receivables"],
    showInSidebar: false,
    gatewayPath: ["Reports", "Sales"],
  },
  {
    id: "reports-sales-performance",
    title: "Sales Performance Report",
    description: "Group → Salesman → Party drill-down with bills, sales, GST, returns and net revenue",
    route: "/reports/sales-performance",
    icon: FileText,
    module: "Reports",
    keywords: ["salesman", "sales team", "performance", "commission", "target", "drill down"],
    showInSidebar: false,
    gatewayPath: ["Reports", "Sales"],
  },
  {
    id: "reports-party-part-sales",
    title: "Party Part-wise Sales Report",
    description: "Per-party part/item sales with rate, discount, and invoice-wise drill-down",
    route: "/reports/party-part-sales",
    icon: FileText,
    module: "Reports",
    keywords: ["party", "part number", "item", "rate history", "customer", "drill down"],
    showInSidebar: false,
    gatewayPath: ["Reports", "Sales"],
  },

  // ==========================================================================
  // SALES
  // ==========================================================================
  {
    id: "sales-quotations",
    title: "Quotations",
    description: "Send price quotes to customers before they commit to a Sales Order",
    route: "/sales/quotations",
    icon: PlusSquare,
    module: "Sales",
    keywords: ["quote", "estimate", "proforma"],
    gatewayPath: ["Transactions", "Sales"],
  },
  {
    id: "sales-quotations-new",
    title: "New Quotation",
    description: "Start a new quotation",
    route: "/sales/quotations/new",
    icon: PlusSquare,
    module: "Sales",
    quickAction: { label: "New Quotation", shortcut: "⌘⌥N" },
    keywords: ["quote", "estimate", "proforma"],
    gatewayPath: ["Transactions", "Sales"],
  },
  {
    id: "orders-new",
    title: "Create Order",
    description: "Start a new sales order",
    route: "/orders/new",
    icon: PlusSquare,
    module: "Sales",
    quickAction: { label: "Create Order", shortcut: "⌘N" },
    perm: "voucher.create",
    gatewayPath: ["Transactions", "Sales"],
  },
  {
    id: "orders",
    title: "Orders",
    description: "All sales orders",
    route: "/orders",
    icon: ShoppingCart,
    module: "Sales",
    gatewayPath: ["Orders"],
  },
  {
    id: "pending",
    title: "Order Control Center",
    description: "Live queue of every pending order, auto-prioritized",
    route: "/pending",
    icon: Boxes,
    module: "Sales",
    keywords: ["awaiting", "open orders"],
    gatewayPath: ["Orders"],
  },
  {
    id: "sales-picking-list",
    title: "Picking List",
    description: "Pick items against an approved order before dispatch",
    route: "/sales/picking-list",
    icon: ClipboardList,
    module: "Sales",
    keywords: ["pick", "warehouse", "pending dispatch"],
    gatewayPath: ["Orders"],
  },
  {
    id: "dispatch",
    title: "Dispatch",
    description: "Dispatch management",
    route: "/dispatch",
    icon: Package,
    module: "Sales",
    keywords: ["shipment", "delivery"],
    gatewayPath: ["Orders"],
  },
  {
    id: "sales-invoices",
    title: "Sales Invoices",
    description: "All sales invoices",
    route: "/sales/invoices",
    icon: Receipt,
    module: "Sales",
    aliases: ["bills"],
    gatewayPath: ["Transactions", "Sales"],
  },
  {
    id: "sales-receive-payment",
    title: "Receive Payment",
    description: "Record a customer payment and allocate it against specific invoices (bill-wise)",
    route: "/sales/receive-payment",
    icon: CreditCard,
    module: "Sales",
    keywords: ["receipt", "collection", "bill-wise"],
    gatewayPath: ["Transactions", "Sales"],
  },
  {
    id: "sales-returns",
    title: "Sales Returns",
    description: "Accept customer returns — posts a Credit Note voucher and restores stock",
    route: "/sales/returns",
    icon: Repeat,
    module: "Sales",
    keywords: ["credit note", "return", "rma"],
    gatewayPath: ["Transactions", "Sales"],
  },
  {
    id: "excel-import",
    title: "Excel Import",
    description: "Bulk import orders from Excel",
    route: "/excel-import",
    icon: UploadCloud,
    module: "Sales",
    keywords: ["bulk", "csv", "upload", "xlsx"],
    showInSidebar: false,
    gatewayPath: ["Orders"],
  },
  {
    id: "parties",
    title: "Customers",
    description: "Customer / party master list",
    route: "/parties",
    icon: Users,
    module: "Sales",
    aliases: ["parties", "clients", "buyers"],
    gatewayPath: ["Masters", "Parties"],
  },
  {
    id: "party-groups",
    title: "Party Groups",
    description: "Group customers/suppliers for pricing & reporting",
    route: "/masters/party-groups",
    icon: Users,
    module: "Sales",
    keywords: ["masters", "grouping"],
    gatewayPath: ["Masters", "Parties"],
  },
  {
    id: "salesman-groups",
    title: "Salesman Groups",
    description: "Group salesmen by team/region for the Sales Performance Report",
    route: "/masters/salesman-groups",
    icon: Users,
    module: "Sales",
    keywords: ["masters", "salesman", "team", "territory"],
    gatewayPath: ["Masters", "Parties"],
  },
  {
    id: "salesmen",
    title: "Salesmen",
    description: "Salesman master — assign to a group, then to parties",
    route: "/masters/salesmen",
    icon: Users,
    module: "Sales",
    keywords: ["masters", "salesman", "sales rep"],
    gatewayPath: ["Masters", "Parties"],
  },
  {
    id: "sales-config",
    title: "Sales Configuration",
    description: "Configure sales workflow defaults",
    route: "/settings/sales-config",
    icon: SettingsIcon,
    module: "Sales",
    keywords: ["config", "settings"],
    perm: "settings.edit",
    gatewayPath: ["Configuration"],
  },

  // ==========================================================================
  // PURCHASE
  // ==========================================================================
  {
    id: "purchase-dashboard",
    title: "Purchase Dashboard",
    description: "Purchase overview",
    route: "/purchase",
    icon: ShoppingBag,
    module: "Purchase",
    gatewayPath: ["Transactions", "Purchase"],
  },
  {
    id: "purchase-orders",
    title: "Purchase Orders",
    description: "All purchase orders",
    route: "/purchase/orders",
    icon: ClipboardList,
    module: "Purchase",
    aliases: ["po"],
    gatewayPath: ["Transactions", "Purchase"],
  },
  {
    id: "purchase-orders-new",
    title: "Create Purchase Order",
    description: "Raise a new purchase order",
    route: "/purchase/orders/new",
    icon: PlusSquare,
    module: "Purchase",
    quickAction: { label: "Create Purchase" },
    perm: "purchase.create",
    gatewayPath: ["Transactions", "Purchase"],
  },
  {
    id: "purchase-grn",
    title: "Goods Receipt Note",
    description: "Record goods received against a purchase order",
    route: "/purchase/grn",
    icon: TruckIcon,
    module: "Purchase",
    aliases: ["grn"],
    gatewayPath: ["Transactions", "Purchase"],
  },
  {
    id: "purchase-invoices",
    title: "Purchase Invoices",
    description: "All purchase invoices",
    route: "/purchase/invoices",
    icon: FileText,
    module: "Purchase",
    gatewayPath: ["Transactions", "Purchase"],
  },
  {
    id: "purchase-returns",
    title: "Purchase Returns",
    description: "Return goods to a supplier",
    route: "/purchase/returns",
    icon: Repeat,
    module: "Purchase",
    gatewayPath: ["Transactions", "Purchase"],
  },
  {
    id: "vendor-claim-register",
    title: "Vendor Claim Register",
    description: "All debit notes — manual returns and QC rejections — by supplier",
    route: "/purchase/vendor-claims",
    icon: Repeat,
    module: "Purchase",
    gatewayPath: ["Reports", "Purchase"],
  },
  {
    id: "purchase-approvals",
    title: "Purchase Approvals",
    description: "Approve or reject pending purchases",
    route: "/purchase/approvals",
    icon: ShieldCheck,
    module: "Purchase",
    perm: "purchase.approve",
    gatewayPath: ["Transactions", "Purchase"],
  },
  {
    id: "purchase-payments",
    title: "Supplier Payments",
    description: "Payments made to suppliers",
    route: "/purchase/payments",
    icon: CreditCard,
    module: "Purchase",
    gatewayPath: ["Transactions", "Purchase"],
  },
  {
    id: "purchase-reports",
    title: "Purchase Reports",
    description: "Purchase analytics and reports",
    route: "/purchase/reports",
    icon: BarChart3,
    module: "Purchase",
    showInSidebar: false,
    gatewayPath: ["Reports", "Purchase"],
  },
  {
    id: "supplier-ledger",
    title: "Supplier Ledger",
    description: "Supplier-wise transaction ledger",
    route: "/purchase/supplier-ledger",
    icon: BookOpen,
    module: "Purchase",
    gatewayPath: ["Reports", "Purchase"],
  },

  // ==========================================================================
  // INVENTORY
  // ==========================================================================
  {
    id: "products",
    title: "Products",
    description: "Product master list",
    route: "/products",
    icon: Package,
    module: "Inventory",
    quickAction: { label: "Create Product" },
    aliases: ["items", "sku"],
    gatewayPath: ["Masters", "Inventory"],
  },
  {
    id: "products-bulk-gst",
    title: "Bulk GST Assign",
    description: "Assign GST rates to products in bulk",
    route: "/products/bulk-gst",
    icon: Tags,
    module: "Inventory",
    keywords: ["gst", "tax", "bulk"],
    gatewayPath: ["Masters", "Inventory"],
  },
  {
    id: "inventory",
    title: "Inventory",
    description: "Current stock levels",
    route: "/inventory",
    icon: Boxes,
    module: "Inventory",
    aliases: ["stock"],
    gatewayPath: ["Reports", "Inventory"],
  },
  {
    id: "inventory-warehouses",
    title: "Warehouses",
    description: "Manage warehouse locations",
    route: "/inventory/warehouses",
    icon: Building2,
    module: "Inventory",
    gatewayPath: ["Masters", "Inventory"],
  },
  {
    id: "inventory-racking",
    title: "Storage Locations",
    description: "Zone, rack and bin locations per warehouse",
    route: "/inventory/racking",
    icon: LayoutGrid,
    module: "Inventory",
    aliases: ["racking", "bins", "zones", "racks"],
    gatewayPath: ["Masters", "Inventory"],
  },
  {
    id: "inventory-batches",
    title: "Batch Tracking",
    description: "Track stock by batch/lot",
    route: "/inventory/batches",
    icon: Layers,
    module: "Inventory",
    aliases: ["lots"],
    gatewayPath: ["Masters", "Inventory"],
  },
  {
    id: "inventory-serials",
    title: "Serial Numbers",
    description: "Track stock by serial number",
    route: "/inventory/serials",
    icon: FilePlus,
    module: "Inventory",
    gatewayPath: ["Masters", "Inventory"],
  },
  {
    id: "inventory-barcodes",
    title: "Barcodes",
    description: "Generate and print product barcodes",
    route: "/inventory/barcodes",
    icon: Barcode,
    module: "Inventory",
    gatewayPath: ["Utilities"],
  },
  {
    id: "inventory-transfers",
    title: "Stock Transfers",
    description: "Move stock between warehouses",
    route: "/inventory/transfers",
    icon: Repeat,
    module: "Inventory",
    gatewayPath: ["Transactions", "Inventory"],
  },
  {
    id: "inventory-stock-take",
    title: "Physical Stock",
    description: "Physical stock take / count",
    route: "/inventory/stock-take",
    icon: ScanLine,
    module: "Inventory",
    aliases: ["stock take", "count"],
    gatewayPath: ["Transactions", "Inventory"],
  },
  {
    id: "inventory-adjustments",
    title: "Stock Adjustments",
    description: "Adjust stock for damage, loss, etc.",
    route: "/inventory/adjustments",
    icon: Scale,
    module: "Inventory",
    gatewayPath: ["Transactions", "Inventory"],
  },

  // ==========================================================================
  // ACCOUNTS (nested: Vouchers / Books / Reports / Receivables & Payables)
  // ==========================================================================
  {
    id: "accounts-vouchers-group",
    title: "Vouchers",
    module: "Accounts",
    description: "Create and manage accounting vouchers",
  },
  {
    id: "accounts-books-group",
    title: "Books & Registers",
    module: "Accounts",
    description: "Day book, cash book and bank book",
  },
  {
    id: "accounts-reports-group",
    title: "Financial Reports",
    module: "Accounts",
    description: "Trial balance, P&L, balance sheet and cash flow",
  },
  {
    id: "accounts-outstanding-group",
    title: "Receivables & Payables",
    module: "Accounts",
    description: "Outstanding dues to be collected or paid",
    showInSidebar: false,
  },

  {
    id: "accounts-voucher-center",
    title: "Voucher Center",
    description: "Central hub for all voucher types",
    route: "/accounts/vouchers",
    icon: Receipt,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    gatewayPath: ["Transactions", "Accounting"],
  },
  {
    id: "accounting-vouchers",
    title: "Vouchers",
    description: "Browse all posted vouchers",
    route: "/accounting/vouchers",
    icon: FilePlus,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    gatewayPath: ["Transactions", "Accounting"],
  },
  {
    id: "accounting-vouchers-new",
    title: "New Voucher",
    description: "Create a new accounting voucher",
    route: "/accounting/vouchers/new",
    icon: PlusSquare,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    quickAction: { label: "Create Voucher" },
    perm: "voucher.create",
    gatewayPath: ["Transactions", "Accounting"],
  },
  {
    id: "accounts-journal",
    title: "Journal Voucher",
    description: "Record a journal entry",
    route: "/vouchers/journal",
    icon: FilePlus,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    aliases: ["jv"],
    perm: "voucher.create",
    gatewayPath: ["Transactions", "Accounting"],
  },
  {
    id: "accounts-contra",
    title: "Contra Voucher",
    description: "Cash ↔ bank transfer entry",
    route: "/vouchers/contra",
    icon: Repeat,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    perm: "voucher.create",
    gatewayPath: ["Transactions", "Accounting"],
  },
  {
    id: "accounts-payment",
    title: "Payment Voucher",
    description: "Record an outgoing payment",
    route: "/vouchers/payment",
    icon: ArrowDownRight,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    perm: "voucher.create",
    gatewayPath: ["Transactions", "Accounting"],
  },
  {
    id: "accounts-receipt",
    title: "Receipt Voucher",
    description: "Record an incoming payment",
    route: "/vouchers/receipt",
    icon: ArrowUpRight,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    perm: "voucher.create",
    gatewayPath: ["Transactions", "Accounting"],
  },
  {
    id: "accounts-debit-note",
    title: "Debit Note",
    description: "Issue a debit note",
    route: "/accounts/debit-note",
    icon: FileText,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    perm: "voucher.create",
    gatewayPath: ["Transactions", "Accounting"],
  },
  {
    id: "accounts-credit-note",
    title: "Credit Note",
    description: "Issue a credit note",
    route: "/accounts/credit-note",
    icon: FileText,
    module: "Accounts",
    parentId: "accounts-vouchers-group",
    perm: "voucher.create",
    gatewayPath: ["Transactions", "Accounting"],
  },

  {
    id: "accounts-ledgers",
    title: "Ledger Accounts",
    description: "Chart of accounts and party ledgers",
    route: "/accounts/ledgers",
    icon: BookOpen,
    module: "Accounts",
    aliases: ["ledger", "coa"],
    gatewayPath: ["Masters", "Accounts"],
  },
  {
    id: "accounts-day-book",
    title: "Day Book",
    description: "All transactions for a given day",
    route: "/accounts/day-book",
    icon: ClipboardList,
    module: "Accounts",
    parentId: "accounts-books-group",
    gatewayPath: ["Reports", "Accounting"],
  },
  {
    id: "accounts-cash-book",
    title: "Cash Book",
    description: "Cash transaction register",
    route: "/accounts/cash-book",
    icon: Wallet,
    module: "Accounts",
    parentId: "accounts-books-group",
    gatewayPath: ["Reports", "Accounting"],
  },
  {
    id: "accounts-bank-book",
    title: "Bank Book",
    description: "Bank transaction register",
    route: "/accounts/bank-book",
    icon: Landmark,
    module: "Accounts",
    parentId: "accounts-books-group",
    gatewayPath: ["Reports", "Accounting"],
  },
  {
    id: "accounts-bank-accounts",
    title: "Bank Accounts",
    description: "Manage your bank accounts — each gets its own ledger automatically",
    route: "/accounts/bank-accounts",
    icon: Landmark,
    module: "Accounts",
    parentId: "accounts-books-group",
    keywords: ["ifsc", "account number", "banking"],
    gatewayPath: ["Masters", "Accounts"],
  },

  {
    id: "accounts-trial-balance",
    title: "Trial Balance",
    description: "Trial balance report",
    route: "/accounts/trial-balance",
    icon: Scale,
    module: "Accounts",
    parentId: "accounts-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Accounting"],
  },
  {
    id: "accounts-profit-loss",
    title: "Profit & Loss",
    description: "Profit and loss statement",
    route: "/accounts/profit-loss",
    icon: PieChart,
    module: "Accounts",
    parentId: "accounts-reports-group",
    aliases: ["p&l", "pnl", "income statement"],
    showInSidebar: false,
    gatewayPath: ["Reports", "Accounting"],
  },
  {
    id: "accounts-balance-sheet",
    title: "Balance Sheet",
    description: "Balance sheet report",
    route: "/accounts/balance-sheet",
    icon: FileSpreadsheet,
    module: "Accounts",
    parentId: "accounts-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Accounting"],
  },
  {
    id: "accounts-cash-flow",
    title: "Cash Flow",
    description: "Cash flow statement",
    route: "/accounts/cash-flow",
    icon: PieChart,
    module: "Accounts",
    parentId: "accounts-reports-group",
    gatewayPath: ["Reports", "Accounting"],
    // NOT hidden / NOT in Report Center yet -- this page is still mock
    // (verified: 0 real Supabase calls). Stays in the sidebar under its
    // native "Financial Reports" group until it's wired to real data,
    // per the no-mock-in-Report-Center rule.
  },

  {
    id: "accounts-receivables",
    title: "Receivables",
    description: "Amounts owed to you",
    route: "/accounts/receivables",
    icon: ArrowUpRight,
    module: "Accounts",
    parentId: "accounts-outstanding-group",
    aliases: ["debtors"],
    showInSidebar: false,
    gatewayPath: ["Reports", "Accounting"],
  },
  {
    id: "accounts-payables",
    title: "Payables",
    description: "Amounts you owe suppliers",
    route: "/accounts/payables",
    icon: ArrowDownRight,
    module: "Accounts",
    parentId: "accounts-outstanding-group",
    aliases: ["creditors"],
    showInSidebar: false,
    gatewayPath: ["Reports", "Accounting"],
  },

  // ==========================================================================
  // INVENTORY REPORTS
  // ==========================================================================
  {
    id: "inv-reports-group",
    title: "Inventory Reports",
    module: "Reports",
    description: "Tally-style inventory reports with drill-down",
    showInSidebar: false,
  },
  {
    id: "inv-reports-dashboard",
    title: "Inventory Dashboard",
    description: "Live stock health — KPIs, alerts and quick links to all inventory reports",
    route: "/reports/inventory",
    icon: Package,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["stock", "inventory", "dashboard", "kpi", "overview"],
  },
  {
    id: "inv-stock-summary",
    title: "Stock Summary",
    description: "Opening · Inward · Outward · Closing with drill-down to every transaction — Tally-style",
    route: "/reports/inventory/stock-summary",
    icon: FileSpreadsheet,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["stock", "summary", "opening", "closing", "inward", "outward", "tally", "stock report"],
    aliases: ["stock summary", "stock report", "inventory summary"],
  },
  {
    id: "inv-tally-stock-summary",
    title: "Stock Summary (Group Drill-down)",
    description: "Hierarchical Stock Group → Item drill-down with a transaction-wise Stock Ledger — Tally-style",
    route: "/reports/inventory/stock-summary-tally",
    icon: FileSpreadsheet,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["stock", "summary", "hierarchical", "group", "ledger", "tally", "drill-down", "expand"],
    aliases: ["stock group drill-down", "stock ledger", "hierarchical stock summary"],
  },
  {
    id: "inv-group-summary",
    title: "Stock Group Summary",
    description: "Stock movement summarised by product group",
    route: "/reports/inventory/group-summary",
    icon: Boxes,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["group", "product group", "stock group"],
  },
  {
    id: "inv-category-summary",
    title: "Stock Category Summary",
    description: "Stock movement summarised by product category",
    route: "/reports/inventory/category-summary",
    icon: Boxes,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["category", "stock category", "category summary"],
  },
  {
    id: "inv-warehouse-summary",
    title: "Warehouse Summary",
    description: "Stock levels and movement per warehouse location",
    route: "/reports/inventory/warehouse-summary",
    icon: Building2,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["warehouse", "location", "godown", "stock"],
  },
  {
    id: "inv-stock-ageing",
    title: "Stock Ageing",
    description: "Stock classified by days since last movement — 0-30, 31-60, 61-90, 90-180, 180-365, 365+",
    route: "/reports/inventory/stock-ageing",
    icon: Clock,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["ageing", "aging", "old stock", "slow moving", "days"],
  },
  {
    id: "inv-dead-stock",
    title: "Dead Stock Report",
    description: "Products with no outward movement for configurable days — identify idle inventory",
    route: "/reports/inventory/dead-stock",
    icon: AlertTriangle,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["dead stock", "idle", "non moving", "stuck inventory"],
  },
  {
    id: "inv-movement-register",
    title: "Stock Movement Register",
    description: "All stock inflows and outflows — Purchase, Sales, Transfers, Adjustments, Returns",
    route: "/reports/inventory/movement-register",
    icon: Activity,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["movement", "register", "inward", "outward", "purchase", "sales", "transfer", "stock ledger"],
    aliases: ["stock ledger", "movement register", "stock register"],
  },
  {
    id: "inv-stock-valuation",
    title: "Stock Valuation",
    description: "Closing stock valued at cost, MRP and selling price with profit potential",
    route: "/reports/inventory/stock-valuation",
    icon: Archive,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["valuation", "value", "cost", "mrp", "profit", "stock value"],
  },
  {
    id: "inv-abc-analysis",
    title: "ABC Analysis",
    description: "Pareto classification — A = top 80% of value, B = next 15%, C = bottom 5%",
    route: "/reports/inventory/abc-analysis",
    icon: BarChart3,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["abc", "pareto", "80-20", "classification", "analysis"],
  },
  {
    id: "inv-fsn-analysis",
    title: "FSN Analysis",
    description: "Fast · Slow · Non-moving classification by sales movement frequency",
    route: "/reports/inventory/fsn-analysis",
    icon: Zap,
    module: "Reports",
    parentId: "inv-reports-group",
    showInSidebar: false,
    gatewayPath: ["Reports", "Inventory"],
    keywords: ["fsn", "fast", "slow", "non moving", "frequency", "velocity"],
  },

  // ==========================================================================
  // GST
  // ==========================================================================
  // Structured as a permanent module architecture (Dashboard / Returns /
  // Reports / Masters / Utilities / Settings), not a flat page dump — planned
  // pages that don't exist yet appear as disabled "Coming soon" placeholders
  // (see NavItem.disabled in ./types.ts) rather than being left out, so the
  // module's real shape is visible today and each placeholder becomes a real
  // page later just by adding its `route` and dropping `disabled`.
  {
    id: "gst-group-dashboard",
    title: "Dashboard",
    module: "GST",
    order: 1,
  },
  {
    id: "gst-dashboard",
    title: "GST Dashboard",
    description: "At-a-glance output tax, ITC, and net payable across periods",
    route: "/gst/dashboard",
    icon: Activity,
    module: "GST",
    parentId: "gst-group-dashboard",
    keywords: ["dashboard", "output tax", "itc", "net payable", "overview"],
    gatewayPath: ["GST"],
  },

  {
    id: "gst-group-returns",
    title: "Returns",
    module: "GST",
    order: 2,
  },
  {
    id: "gst-filing",
    title: "GST Filing",
    description: "Prepare, generate, file, and revise GSTR-1/3B returns with period locking and approvals",
    route: "/gst/filing",
    icon: FilePlus,
    module: "GST",
    parentId: "gst-group-returns",
    order: 1,
    keywords: ["gstr1", "gstr3b", "filing", "arn", "return", "lock", "approval", "revision"],
    gatewayPath: ["GST", "Returns"],
  },
  {
    id: "gst-gstr-1",
    title: "GSTR-1",
    description: "Invoice-wise B2B/B2C outward supplies with GSTIN and tax breakup",
    route: "/gst/gstr-1",
    icon: Receipt,
    module: "GST",
    parentId: "gst-group-returns",
    order: 2,
    keywords: ["gstr1", "returns", "filing", "b2b", "b2c"],
    gatewayPath: ["GST", "Returns"],
  },
  {
    id: "gst-gstr-3b",
    title: "GSTR-3B",
    description: "Outward tax liability vs input tax credit, net payable",
    route: "/gst/gstr-3b",
    icon: Scale,
    module: "GST",
    parentId: "gst-group-returns",
    order: 3,
    keywords: ["gstr3b", "returns", "filing"],
    gatewayPath: ["GST", "Returns"],
  },
  {
    id: "gst-gstr-2-reconciliation",
    title: "GSTR-2B Reconciliation",
    description: "Import GSTR-2A/2B and reconcile against the purchase register for ITC matching",
    route: "/gst/gstr-2-reconciliation",
    icon: Layers,
    module: "GST",
    parentId: "gst-group-returns",
    order: 4,
    keywords: ["gstr2a", "gstr2b", "itc", "reconciliation", "import"],
    gatewayPath: ["GST"],
  },
  {
    id: "gst-gstr-9",
    title: "GSTR-9 / 9C",
    description: "Annual summary and books-vs-filed-returns reconciliation",
    route: "/gst/gstr-9",
    icon: Archive,
    module: "GST",
    parentId: "gst-group-returns",
    order: 5,
    keywords: ["gstr9", "gstr9c", "annual", "reconciliation"],
    gatewayPath: ["GST", "Returns"],
  },

  {
    id: "gst-group-reports",
    title: "Reports",
    module: "GST",
    order: 3,
  },
  {
    id: "gst-summary",
    title: "GST Summary",
    description: "GST liability and input tax credit summary",
    route: "/gst/summary",
    icon: PieChart,
    module: "GST",
    parentId: "gst-group-reports",
    order: 1,
    keywords: ["tax", "gstr", "returns"],
    gatewayPath: ["GST", "GST Reports"],
  },
  {
    id: "gst-tax-register",
    title: "Tax Register",
    description: "Combined output and input tax register, chronological",
    route: "/gst/tax-register",
    icon: BookOpen,
    module: "GST",
    parentId: "gst-group-reports",
    order: 2,
    keywords: ["tax", "register", "input", "output"],
    gatewayPath: ["GST", "GST Reports"],
  },
  {
    id: "gst-hsn-summary",
    title: "HSN Summary",
    description: "Sales grouped by HSN code and GST rate",
    route: "/gst/hsn-summary",
    icon: Barcode,
    module: "GST",
    parentId: "gst-group-reports",
    order: 3,
    keywords: ["hsn", "gstr1"],
    gatewayPath: ["GST", "GST Reports"],
  },
  {
    id: "gst-hsn-summary-purchase",
    title: "HSN Summary (Purchase)",
    description: "Purchases grouped by HSN code and GST rate",
    route: "/gst/hsn-summary-purchase",
    icon: Barcode,
    module: "GST",
    parentId: "gst-group-reports",
    order: 4,
    keywords: ["hsn", "purchase", "input tax"],
    gatewayPath: ["GST", "GST Reports"],
  },

  {
    id: "gst-group-masters",
    title: "Masters",
    module: "GST",
    order: 4,
  },
  {
    id: "gst-hsn-master",
    title: "HSN Master",
    description: "HSN/SAC codes, Goods/Service type, UQC, and effective-dated GST rates — used everywhere HSN appears",
    route: "/gst/hsn-master",
    icon: ScanLine,
    module: "GST",
    parentId: "gst-group-masters",
    order: 1,
    keywords: ["hsn", "sac", "gst rate", "tax profile", "uqc"],
    gatewayPath: ["Masters", "GST & Tax"],
  },

  {
    id: "gst-group-utilities",
    title: "Utilities",
    module: "GST",
    order: 5,
  },
  {
    id: "gst-portal-sync",
    title: "GST Portal Sync",
    description: "Direct GSTN/GSP API connection for filing and 2A/2B pull",
    icon: UploadCloud,
    module: "GST",
    parentId: "gst-group-utilities",
    order: 1,
    disabled: true,
    gatewayPath: ["GST"],
  },
  {
    id: "gst-einvoice-register",
    title: "e-Invoice Register",
    description: "All e-Invoices generated across sales invoices, with IRN status",
    route: "/gst/einvoice-register",
    icon: FileText,
    module: "GST",
    parentId: "gst-group-utilities",
    order: 2,
    keywords: ["einvoice", "irn", "ack"],
    gatewayPath: ["GST"],
  },
  {
    id: "gst-ewaybill-register",
    title: "e-Way Bill Register",
    description: "All e-Way Bills generated across sales invoices, with validity status",
    route: "/gst/ewaybill-register",
    icon: TruckIcon,
    module: "GST",
    parentId: "gst-group-utilities",
    order: 3,
    keywords: ["ewaybill", "e-way bill", "vehicle", "transport"],
    gatewayPath: ["GST"],
  },

  {
    id: "gst-group-settings",
    title: "Settings",
    module: "GST",
    order: 6,
  },
  {
    id: "gst-configuration",
    title: "GST Configuration",
    description: "GSTIN registrations, HSN compliance, e-Invoice/e-Way Bill applicability, return preferences",
    route: "/gst/configuration",
    icon: SettingsIcon,
    module: "GST",
    parentId: "gst-group-settings",
    keywords: ["gstin", "registration", "e-invoice", "e-way bill", "config"],
    gatewayPath: ["GST"],
  },

  // ==========================================================================
  // PRICING & PROMOTION ENGINE
  // ==========================================================================
  // Phase 1B — only a diagnostic tool exists so far (no Price List/Discount/
  // Scheme UI yet, that's Phase 1C/1D/2). Gated the same way GST
  // Configuration is (settings.edit) — this reads raw pricing_rules data,
  // not a general-access screen.
  {
    id: "pricing-price-lists",
    title: "Price Lists",
    description: "Retail/Wholesale/Dealer/... price lists the Pricing Engine resolves against",
    route: "/pricing/price-lists",
    icon: Tags,
    module: "Pricing",
    order: 1,
    keywords: ["pricing", "price list", "dealer price", "wholesale", "retail"],
    gatewayPath: ["Masters", "Pricing"],
  },
  {
    id: "pricing-rules",
    title: "Pricing Rules",
    description: "Party/Item/Category discount rules the Pricing Engine applies on top of the base price list",
    route: "/pricing/rules",
    icon: Zap,
    module: "Pricing",
    order: 2,
    keywords: ["pricing", "discount", "rule", "scheme", "party discount", "item discount"],
    gatewayPath: ["Masters", "Pricing"],
  },
  {
    id: "pricing-test-bench",
    title: "Pricing Test Bench",
    description: "Run calculatePricing() against real data — trace, explain, rejected rules, snapshot preview",
    route: "/pricing/test-bench",
    icon: Calculator,
    module: "Pricing",
    order: 3,
    keywords: ["pricing", "discount", "scheme", "test", "trace", "explain", "rule engine"],
    gatewayPath: ["Utilities"],
  },

  // ==========================================================================
  // SETTINGS — company/user/security identity (module "Settings")
  // ==========================================================================
  {
    id: "profile",
    title: "Profile",
    description: "Your personal profile",
    route: "/profile",
    icon: User,
    module: "Settings",
  },
  {
    id: "settings",
    title: "Settings",
    description: "App preferences",
    route: "/settings",
    icon: SettingsIcon,
    module: "Settings",
  },
  {
    id: "business-profile",
    title: "Business Profile",
    description: "Company details, GSTIN, PAN, bank info",
    route: "/settings/business-profile",
    icon: Landmark,
    module: "Settings",
    perm: "business.edit",
    gatewayPath: ["Administration", "Company"],
  },
  {
    id: "users-access-group",
    title: "Users & Access",
    module: "Settings",
    description: "Who has access to this company, and how permissions work",
  },
  {
    id: "company-users",
    title: "Company Users",
    description: "Manage users in this company",
    route: "/settings/company-users",
    icon: Users,
    module: "Settings",
    parentId: "users-access-group",
    perm: "team.manage",
    gatewayPath: ["Administration", "Company"],
  },
  {
    id: "permission-system",
    title: "Permission System",
    description: "Choose how permissions work for this company",
    route: "/settings/permission-system",
    icon: ShieldCheck,
    module: "Settings",
    parentId: "users-access-group",
    perm: "team.manage",
    gatewayPath: ["Administration", "Security & Access"],
  },

  // ==========================================================================
  // CONFIGURATION — business behavior rules (module "Configuration")
  // ==========================================================================
  {
    id: "config-sales-group",
    title: "Sales",
    module: "Configuration",
    description: "Sales workflow, numbering and rounding rules",
  },
  {
    id: "voucher-numbering",
    title: "Voucher Numbering",
    description: "Configure voucher numbering series",
    route: "/settings/voucher-numbering",
    icon: Receipt,
    module: "Configuration",
    parentId: "config-sales-group",
    perm: "settings.edit",
    gatewayPath: ["Configuration"],
  },
  {
    id: "round-off-settings",
    title: "Round Off Settings",
    description: "Enable rounding on invoice totals, choose the rounding method, and pick which vouchers apply it",
    route: "/settings/round-off",
    icon: Calculator,
    module: "Configuration",
    parentId: "config-sales-group",
    keywords: ["round off", "rounding", "nearest", "precision", "ledger"],
    gatewayPath: ["Configuration"],
  },
  {
    id: "config-inventory-group",
    title: "Inventory",
    module: "Configuration",
    description: "Units, bins and warehouse feature toggles",
  },
  {
    id: "measurement-units",
    title: "Measurement Units",
    description: "Manage units, categories and conversions used across Purchase, Sales & Inventory",
    route: "/settings/measurement-units",
    icon: Layers,
    module: "Configuration",
    parentId: "config-inventory-group",
    perm: "settings.edit",
    gatewayPath: ["Masters", "Inventory"],
  },
  {
    id: "inventory-settings",
    title: "Inventory Settings",
    description: "Bin management and warehouse feature toggles used by GRN, Dispatch, Stock Transfer, Stock Take, and Picking List",
    route: "/settings/inventory",
    icon: SettingsIcon,
    module: "Configuration",
    parentId: "config-inventory-group",
    keywords: ["bin", "warehouse", "put-away", "zone", "rack", "batch", "serial", "cycle count"],
    gatewayPath: ["Configuration"],
  },
  {
    id: "config-accounting-group",
    title: "Accounting",
    module: "Configuration",
    description: "Note categories, accounting lock and financial years",
  },
  {
    id: "financial-note-categories",
    title: "Financial Note Categories",
    description: "Debit/Credit Note adjustment categories and default ledgers",
    route: "/settings/financial-note-categories",
    icon: Tags,
    module: "Configuration",
    parentId: "config-accounting-group",
    perm: "settings.edit",
    gatewayPath: ["Configuration"],
  },
  {
    id: "accounting-lock",
    title: "Accounting Lock",
    description: "Lock accounting periods from further edits",
    route: "/settings/accounting-lock",
    icon: ShieldCheck,
    module: "Configuration",
    parentId: "config-accounting-group",
    perm: "settings.edit",
    gatewayPath: ["Configuration"],
  },
  {
    id: "financial-years",
    title: "Financial Years",
    description: "Open/close financial years — a closed year blocks new posting and posted-voucher deletion inside it",
    route: "/settings/financial-years",
    icon: ShieldCheck,
    module: "Configuration",
    parentId: "config-accounting-group",
    perm: "settings.edit",
    gatewayPath: ["Administration", "Company"],
  },

  // ==========================================================================
  // ADMINISTRATION — data & system maintenance (module "Administration")
  // ==========================================================================
  {
    id: "approval-center",
    title: "Approval Center",
    description: "Pending approvals across modules",
    route: "/approval-center",
    icon: ShieldCheck,
    module: "Administration",
    gatewayPath: ["Administration"],
  },
  {
    id: "audit-logs",
    title: "Audit Logs",
    description: "System-wide audit trail",
    route: "/admin/audit-logs",
    icon: ShieldCheck,
    module: "Administration",
    perm: "audit.view",
    gatewayPath: ["Administration"],
  },
  {
    id: "print-copy-configuration",
    title: "Print Copy Configuration",
    description: "Configure the copy labels offered when printing any document (Original, Duplicate, Office Copy, etc.)",
    route: "/settings/print-copies",
    icon: FileText,
    module: "Administration",
    perm: "settings.edit",
    keywords: ["print", "copy", "original", "duplicate", "transporter"],
    gatewayPath: ["Configuration"],
  },
  {
    id: "print-profiles",
    title: "Print Profiles",
    description: "Page size, margins, sections, and watermark for each document's default print layout",
    route: "/settings/print-profiles",
    icon: FileText,
    module: "Administration",
    perm: "settings.edit",
    keywords: ["print", "template", "page size", "margin", "watermark", "layout"],
    gatewayPath: ["Configuration"],
  },
  {
    id: "opening-balance-migration",
    title: "Opening Balance / Migration",
    description: "Migrate closing balances from Tally/Busy/Easy into RD Pro as reconciled opening balances",
    route: "/settings/opening-balance-migration",
    icon: ArrowLeftRight,
    module: "Administration",
    keywords: ["migration", "tally", "busy", "easy", "opening balance"],
    // showInSidebar: false keeps Classic Tree exactly as it was — this item
    // was intentionally never in the sidebar (only Settings.tsx + Search),
    // Gateway mode is a new way to reach it, not a new Classic sidebar row.
    showInSidebar: false,
    gatewayPath: ["Utilities"],
  },
  {
    id: "backup-restore",
    title: "Backup & Restore",
    description: "Create encrypted backups, download them, or restore into a new company (owner only)",
    route: "/settings/backup-restore",
    icon: DatabaseBackup,
    module: "Administration",
    perm: "owner",
    showInSidebar: false,
    gatewayPath: ["Administration"],
  },
  {
    id: "maintenance",
    title: "Maintenance",
    description: "Rebuild ledger balances and other data-recovery actions (Owner/Admin only)",
    route: "/settings/maintenance",
    icon: Wrench,
    module: "Administration",
    perm: "maintenance",
    showInSidebar: false,
    gatewayPath: ["Administration"],
  },
  {
    id: "danger-zone",
    title: "Danger Zone",
    description: "Archive or permanently delete this company (owner only)",
    route: "/settings/danger-zone",
    icon: ShieldAlert,
    module: "Administration",
    perm: "owner",
    showInSidebar: false,
    gatewayPath: ["Administration"],
  },

  // ==========================================================================
  // HELP & SUPPORT — planned, not yet built. Disabled placeholders per the
  // same precedent as gst-portal-sync above: no `route` (nothing to link
  // to), so they render greyed-out and are excluded from Command Search
  // automatically. Becomes real later by adding `route` and dropping
  // `disabled` — no other change needed.
  // ==========================================================================
  {
    id: "help-center",
    title: "Help Center",
    description: "Browse help articles and documentation",
    icon: HelpCircle,
    module: "Administration",
    disabled: true,
    showInSidebar: false,
    gatewayPath: ["Help & Support"],
  },
  {
    id: "help-getting-started",
    title: "Getting Started",
    description: "Onboarding walkthrough for new users",
    icon: BookOpen,
    module: "Administration",
    disabled: true,
    showInSidebar: false,
    gatewayPath: ["Help & Support"],
  },
  {
    id: "help-keyboard-shortcuts",
    title: "Keyboard Shortcuts",
    description: "Full list of keyboard shortcuts",
    icon: Keyboard,
    module: "Administration",
    disabled: true,
    showInSidebar: false,
    gatewayPath: ["Help & Support"],
  },
  {
    id: "help-contact-support",
    title: "Contact Support",
    description: "Reach the RD Pro support team",
    icon: Mail,
    module: "Administration",
    disabled: true,
    showInSidebar: false,
    gatewayPath: ["Help & Support"],
  },

  // ==========================================================================
  // DEALER PORTAL
  // ==========================================================================
  {
    id: "dealer-applications",
    title: "Dealer Applications",
    description: "Review incoming dealer/retailer applications",
    route: "/settings/dealer-applications",
    icon: ClipboardList,
    module: "Dealer Portal",
    perm: "settings.edit",
    gatewayPath: ["Administration", "Company"],
  },
];
